import { Category } from "./entities/category.entity";

export const seedCategories = [
    {
        id: '',
        nameEN: 'All',
        nameDE: 'Alle',
        nameFR: 'Tout',
        nameIT: 'Tutto',
    },
    {
        id: '',
        nameEN: 'Dance',
        nameDE: 'Tanzen',
        nameFR: 'Danse',
        nameIT: 'Danza',
    },
    {
        id: '',
        nameEN: 'Sports',
        nameDE: 'Sport',
        nameFR: 'Des sports',
        nameIT: 'Gli sport',
    },
    {
        id: '',
        nameEN: 'Music',
        nameDE: 'Muziek',
        nameFR: 'Musique',
        nameIT: 'Musica',
    },
    {
        id: '',
        nameEN: 'Art',
        nameDE: 'Kunst',
        nameFR: 'Art',
        nameIT: 'Arte',
    },
    {
        id: '',
        nameEN: 'Educational',
        nameDE: 'Leerzaam',
        nameFR: 'Éducatif',
        nameIT: 'Educativa',
    },
    {
        id: '',
        nameEN: 'Birthdays',
        nameDE: 'Verjaardagen',
        nameFR: 'Anniversaires',
        nameIT: 'Compleanni',
    },
    {
        id: '',
        nameEN: 'Camps',
        nameDE: 'Kampen',
        nameFR: 'Campements',
        nameIT: 'Campi',
    },
    {
        id: '',
        nameEN: 'Wednesday',
        nameDE: 'Woensdag',
        nameFR: 'Mercredi',
        nameIT: 'Mercoledì',
    },
    {
        id: '',
        nameEN: 'Today',
        nameDE: 'Vandaag',
        nameFR: "Aujourd'hui",
        nameIT: 'Oggi',
    },
    {
        id: '',
        nameEN: 'This Weekend',
        nameDE: 'Dit weekend',
        nameFR: 'Cette fin de semaine',
        nameIT: 'Questo fine settimana',
    },
    {
        id: '',
        nameEN: 'Free',
        nameDE: 'Vrij',
        nameFR: 'Gratuit',
        nameIT: 'Gratuita',
    },
] as Category[];